### DISCUSSION TITLE
Camera: reset trim -> Specs Redefine / Fix and improve

### DISCUSSION THREAD

**Discussion by Minims** [sca075/mqtt_vacuum_camera#236] [Ideas]
Hello,

In 2024.8.0, does this action

```
action: mqtt_vacuum_camera.reset_trims
data: {}
target:
  entity_id: camera.roger_camera
```

is supposed to be the same as 
Integration > MQTT Vacuum Camera > Configure > Advanced options > Reset trims ?

My problems is that i have configure camera for Floor-0. All is OK. Then i load the Floor-1 Map. The map is cropped and not centered.

I run : Integration > MQTT Vacuum Camera > Configure > Advanced options > Reset trims.

And the floor-1 map is OK.

I would expect the actions does the same thing, but it's currently not the case.

might be related to https://github.com/sca075/mqtt_vacuum_camera/discussions/207
but don't want to hijack this discussion.

Thanks for the help.

**Comment by sca075** [comment]
@Minims 
you are correct he action setup should be something like:
```yaml
action: mqtt_vacuum_camera.reset_trims
target:
  entity_id: camera.roger_camera
data: {}
```
Reload Trims with this action will actually reset the trims and reload the camera at the same time.  The point of this action is to be used when the vacuum actually rescan the floor. If the Floor - 1 isn't centered reset_trim might solve the image margining, unless if there are actually __margins setup in the camera  configuration..__ that honestly if it is the case we might reset as well.
 
Are you using the maploader on Rand256?  If yes I would give it a try.

When you use  __Integration > MQTT Vacuum Camera > Configure > Advanced options > Reset trims__ and then __reload __ the camera  after the vacuum completed the scan or load a second map the image should be re-trim. Same as running the service.

As I'm still running Rand256, and I know it is possible to save multiple maps... can you please be more precise and let me know if you intend to use the same vacuum on both floors? This is actually interesting and I don't know if we can "automate this process" using the Camera code.

I will in any cases check (and change probably something on the reload "action") as per I noticed there could be some improvement, it looks that with more then one vacuum probably this action need to be target  too.

Hope this help, anytime, please let me know if we can improve something here.

**Reply by Minims** [reply]
> Are you using the maploader on Rand256? If yes I would give it a try.

No i am just using Valetudo RE 10.10. And i'm loading the map with this service.

```
  - icon: mdi:home-floor-0
    tooltip: Rez de Chaussée
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roger_roborock_s5
        command: load_map
        params:
          name: Rez de Chaussee
  - icon: mdi:reload
    tooltip: Reload
    tap_action:
      action: call-service
      service: mqtt_vacuum_camera.reload
  - icon: mdi:box-cutter
    tooltip: Trim
    tap_action:
      action: call-service
      service: mqtt_vacuum_camera.reset_trims
      target:
        entity_id: camera.roger_camera
```

> When you use Integration > MQTT Vacuum Camera > Configure > Advanced options > Reset trims and then __reload __ the camera after the vacuum completed the scan or load a second map the image should be re-trim. Same as running the service.

This is working great. 

But service/action call `mqtt_vacuum_camera.reset_trims` does nothing. Map is not re-trim.

> let me know if you intend to use the same vacuum on both floors

Yes. I use my S5 on both floors. I have save my 2 maps.
On floor change; i 'm loading the map : 

```
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roger_roborock_s5
        command: load_map
        params:
          name: Rez de Chaussee
```

Trim

```
      service: mqtt_vacuum_camera.reset_trims
      target:
        entity_id: camera.roger_camera
```

Reload by security, but it seems trim already did it.
```
      service: mqtt_vacuum_camera.reload
```

**Reply by sca075** [reply]
Okay "ValetudoRe = Rand256 is the same",  then I will check the reset_trims "Action" by the way.. would you please try this:
```yaml
  - icon: mdi:home-floor-0
    tooltip: Rez de Chaussée
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roger_roborock_s5
        command: load_map
        params:
          name: Rez de Chaussee
  - icon: mdi:reload
    tooltip: Reload
    tap_action:
      action: call-service
      service: mqtt_vacuum_camera.reload
  - icon: mdi:box-cutter
    tooltip: Trim
    tap_action:
      action: call-service
      service: mqtt_vacuum_camera.reset_trims
      target:
        entity_id: camera.roger_camera
      data: {}
```
Adding the "data" = {} for the service, this config is in the card correct? I would check if I can reproduce this ;)

Additionally __reload__ is not necessary when you un the __reset_trims__.

**Reply by Minims** [reply]
I have tried this 

```
  - icon: mdi:box-cutter
    tooltip: Trim
    tap_action:
      action: call-service
      service: mqtt_vacuum_camera.reset_trims
      target:
        entity_id: camera.roger_camera
      data: {}
```

Reload is working, but trim does nothing.

FYI, doing the same thing in Developpement > Actions does not work too.

```
action: mqtt_vacuum_camera.reset_trims
data: {}
target:
  entity_id: camera.roger_camera
```
