### DISCUSSION TITLE
Cant send vacuum out to clean: Action xiaomi_miio.vacuum_clean_zone not found, configuration error on my (user) side?

### DISCUSSION THREAD

**Discussion by borgqueenx** [sca075/mqtt_vacuum_camera#313] [Q&A] [answered]
No matter if i try to clean a room, pin and go or use a zone, my robot vacuum wont start working, since i moved house.

Im getting the errors:
Entity vacuum.valetudo_occasionalmurkyguanaco doesn't support the action vacuum.send_command.
Action xiaomi_miio.vacuum_goto not found.
Action xiaomi_miio.vacuum_clean_zone not found.

Here is my configuration:
```
`type: custom:xiaomi-vacuum-map-card
language: en
map_source:
  camera: camera.valetudo_x40_ultra_occasionalmurkyguanaco_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_occasionalmurkyguanaco
vacuum_platform: Hypfer/Valetudo
internal_variables:
  topic: valetudo/OccasionalMurkyGuanaco
card_mod:
  style: |
    ha-card {
      --map-card-room-label-color: white;
      --map-card-room-icon-background-color: white;
      --map-card-room-label-font-size: 17px;
    }
    svg text {
      stroke: black;
      stroke-width: 1px;
      font-weight= bold;
    }
map_modes:
  - name: Obstacles View
    icon: mdi:map-marker
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 100
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: mqtt_vacuum_camera.obstacle_view
      service_data:
        coordinates_x: "[[point_x]]"
        coordinates_y: "[[point_y]]"
      target:
        entity_id: camera.valetudo_x40_ultra_occasionalmurkyguanaco_camera
      variables: {}
  - name: Zone schoonmaak
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: "[[selection]]"
        repeats: "[[repeats]]"
        entity_id: "[[entity_id]]"
    predefined_selections: []
    variables: {}
  - name: Pin & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_goto
      service_data:
        x_coord: "[[point_x]]"
        y_coord: "[[point_y]]"
        entity_id: "[[entity_id]]"
    predefined_selections: []
    variables: {}
  - name: Kamers
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: ROOM
    id_type: number
    max_selections: 999
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        entity_id: "[[entity_id]]"
        params:
          - segments: "[[selection]]"
            repeat: "[[repeats]]"
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:broom
          x: 2755
          "y": 2700
        label:
          text: Kitchen
          x: 2755
          "y": 2700
          offset_y: 35
        outline:
          - - 2460
            - 2495
          - - 3050
            - 2495
          - - 3050
            - 2905
          - - 2460
            - 2905
      - id: "2"
        icon:
          name: mdi:broom
          x: 2457
          "y": 2797
        label:
          text: Bathroom
          x: 2457
          "y": 2797
          offset_y: 35
        outline:
          - - 2390
            - 2690
          - - 2525
            - 2690
          - - 2525
            - 2905
          - - 2390
            - 2905
      - id: "3"
        icon:
          name: mdi:broom
          x: 3262
          "y": 2740
        label:
          text: Living Room
          x: 3262
          "y": 2740
          offset_y: 35
        outline:
          - - 3050
            - 2545
          - - 3475
            - 2545
          - - 3475
            - 2935
          - - 3050
            - 2935
      - id: "4"
        icon:
          name: mdi:broom
          x: 2767
          "y": 3127
        label:
          text: Hallway
          x: 2767
          "y": 3127
          offset_y: 35
        outline:
          - - 2385
            - 2890
          - - 3150
            - 2890
          - - 3150
            - 3365
          - - 2385
            - 3365
      - id: "6"
        icon:
          name: mdi:broom
          x: 3312
          "y": 3137
        label:
          text: Dining Room
          x: 3312
          "y": 3137
          offset_y: 35
        outline:
          - - 3150
            - 2915
          - - 3475
            - 2915
          - - 3475
            - 3360
          - - 3150
            - 3360
      - id: "7"
        icon:
          name: mdi:broom
          x: 2822
          "y": 3255
        label:
          text: Toilet
          x: 2822
          "y": 3255
          offset_y: 35
        outline:
          - - 2785
            - 3195
          - - 2860
            - 3195
          - - 2860
            - 3315
          - - 2785
            - 3315
      - id: "8"
        icon:
          name: mdi:broom
          x: 2582
          "y": 3200
        label:
          text: Guest Room
          x: 2582
          "y": 3200
          offset_y: 35
        outline:
          - - 2400
            - 3035
          - - 2765
            - 3035
          - - 2765
            - 3365
          - - 2400
            - 3365
    variables: {}
append_icons: false
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: cleaning
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: error
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:pause
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: docked
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: idle
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: error
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:stop
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: docked
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: idle
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: error
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: docked
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - menu_id: fan_speed
    icon: valetudo:fan-medium
    label: low
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: low
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: low
  - menu_id: fan_speed
    icon: valetudo:fan-medium
    label: Medium
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: medium
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: medium
  - menu_id: fan_speed
    icon: valetudo:fan-high
    label: high
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: high
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: high
  - menu_id: fan_speed
    icon: valetudo:fan-turbo
    label: max
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: max
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: max
  - type: menu
    menu_id: mopping_mode
    icon_id: moe
    entity: select.valetudo_occasionalmurkyguanaco_water
    available_values_attribute: options
    icon: mdi:water
    icon_mapping:
      min: valetudo:water-min
      low: valetudo:water-low
      medium: valetudo:water-medium
      high: valetudo:water-high
      max: valetudo:water-max
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
  - type: menu
    menu_id: water_box_mode
    icon_id: water_box_mode
    entity: select.valetudo_occasionalmurkyguanaco_mode
    available_values_attribute: options
    icon: mdi:water
    icon_mapping:
      vacuum_and_mop: valetudo:mode-vacuum-and-mop
      vacuum_then_mop: valetudo:mode-vacuum-then-mop
      mop: mdi:waves
      vacuum: mdi:car-turbocharger
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
append_tiles: true
tiles:
  - tile_id: error_messages
    entity: sensor.valetudo_occasionalmurkyguanaco_error
    label: Error Messages
    icon: mdi:alert-circle-outline
    tooltip: Water Intensity
  - tile_id: fan_speed
    entity: sensor.valetudo_occasionalmurkyguanaco_sensor_cleaning
    label: Sensor Cleaning Left
    icon: mdi:lotion-outline
    tooltip: Cleaning Mode
    multiplier: 0.0166667
    precision: 0
    unit: h
`
```

Would appriciate any assistance to get this back working!

**Comment by sca075** [comment]
@borgqueenx it looks you manually configured the card.. 
```yaml
map_modes:
  - name: Zone cleanup
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 100
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: mqtt.publish
      evaluate_data_as_template: true
      service_data:
        topic: "[[topic]]/ZoneCleaningCapability/start/set"
        payload: >-
          {"zones": [{%for s in ('[[selection]]')|from_json %}{ "points": {"pA":
          { "x": {{s[0]}}, "y": {{s[1]}} }, "pB": { "x": {{s[2]}}, "y": {{s[1]}}
          }, "pC": { "x": {{s[2]}}, "y": {{s[3]}} }, "pD": { "x": {{s[0]}}, "y":
          {{s[3]}} } }, "iterations": [[repeats]]}{%if not
          loop.last%},{%endif%}{%endfor%}]}
    predefined_selections: []
    variables: {}
  - name: Pin & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 100
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: mqtt.publish
      service_data:
        topic: "[[topic]]/GoToLocationCapability/go/set"
        payload: "{ \"coordinates\": { \"x\": [[point_x]], \"y\": [[point_y]] } }"
    predefined_selections: []
    variables: {}
  - name: Obstacles View
    icon: mdi:map-marker
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 100
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: mqtt_vacuum_camera.obstacle_view
      service_data:
        coordinates_x: "[[point_x]]"
        coordinates_y: "[[point_y]]"
      target:
        entity_id: camera.valetudo_x40_ultra_occasionalmurkyguanaco_camera
      variables: {}
additional_presets: []

```

I guess if you start a new card setup.
1) select the vacuum entity
2) select the platform
3) select the camera.
4) Generate Room config.
6) edit in yaml and adjust it as you wish. 
The up posted yaml do not include the command for the segment clean as my vacuum do not use segments so pin and go and zone clean should work with the code I posted. As you can see there are the MQTT commands for the vacuum.

The clean segment topic is ```/MapSegmentationCapability/clean/set````

Hope this helps.

**Comment by borgqueenx** [comment]
im trying my best to fix it with no luck. another weird issue is, probably with the xiaomi vacuum card, if i click create room configuration, it copies rooms into the yaml but also the previous rooms. i tried to re-create the card a few times now, and now i have like 70 rooms from clicking that button.
(just clicking once create room configuration)

EDIT: When doing the exact as you described above, the robot isnt responding. Instead, it shows a "ok", not giving a error. But it simply doesn't do anything.

**Reply by borgqueenx** [reply]
The code in your reply fixed it, though, many thanks. The code doesn't include rooms, however.
When making the following default configuration, it doesn't work.
1. create custom vacuum map card.
2. select entity, camera, then create room configuration, then make static configuration.
3. Select pin & go, rooms or zones, the card gives a OK, but the robot doesn't do anything.

This is probably a issue for the xiaomi map card, though?

**Reply by sca075** [reply]
> The code in your reply fixed it, though, many thanks. The code doesn't include rooms, however.
> 
> When making the following default configuration, it doesn't work.
> 
> 1. create custom vacuum map card.
> 
> 2. select entity, camera, then create room configuration, then make static configuration.
> 
> 3. Select pin & go, rooms or zones, the card gives a OK, but the robot doesn't do anything.
> 
> 
> 
> This is probably a issue for the xiaomi map card, though?

Listen the robot use valetudo right? 
The card has a problem with the rooms as you wrote but it should be farelly easy to let it work.

Give me a second I will correct the configuration you posted before and then it should be just copy past I might still have the sintax of the card for it.

**Comment by sca075** [comment]
Yes there's a problem with the card and it make the rooms several times

**Comment by sca075** [comment, marked as answer]
``` yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.valetudo_x40_ultra_occasionalmurkyguanaco_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_occasionalmurkyguanaco
vacuum_platform: Hypfer/Valetudo
internal_variables:
  topic: valetudo/OccasionalMurkyGuanaco
map_modes:
  - name: Zone cleanup
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 100
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: mqtt.publish
      evaluate_data_as_template: true
      service_data:
        topic: "[[topic]]/ZoneCleaningCapability/start/set"
        payload: >-
          {"zones": [{%for s in ('[[selection]]')|from_json %}{ "points": {"pA":
          { "x": {{s[0]}}, "y": {{s[1]}} }, "pB": { "x": {{s[2]}}, "y": {{s[1]}}
          }, "pC": { "x": {{s[2]}}, "y": {{s[3]}} }, "pD": { "x": {{s[0]}}, "y":
          {{s[3]}} } }, "iterations": [[repeats]]}{%if not
          loop.last%},{%endif%}{%endfor%}]}
    predefined_selections: []
    variables: {}
  - name: Pin & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 100
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: mqtt.publish
      service_data:
        topic: "[[topic]]/GoToLocationCapability/go/set"
        payload: "{ \"coordinates\": { \"x\": [[point_x]], \"y\": [[point_y]] } }"
    predefined_selections: []
    variables: {}
   - name: Rooms
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: ROOM
    max_selections: 999
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: mqtt.publish
      service_data:
        topic: "[[topic]]/MapSegmentationCapability/clean/set"
        payload: >-
          {"segment_ids": [[selection]], "iterations": [[repeats]],
          "customOrder": true}
  - name: Obstacles View
    icon: mdi:map-marker
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 100
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: mqtt_vacuum_camera.obstacle_view
      service_data:
        coordinates_x: "[[point_x]]"
        coordinates_y: "[[point_y]]"
      target:
        entity_id: camera.valetudo_x40_ultra_occasionalmurkyguanaco_camera
      variables: {}
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:broom
          x: 2755
          "y": 2700
        label:
          text: Kitchen
          x: 2755
          "y": 2700
          offset_y: 35
        outline:
          - - 2460
            - 2495
          - - 3050
            - 2495
          - - 3050
            - 2905
          - - 2460
            - 2905
      - id: "2"
        icon:
          name: mdi:broom
          x: 2457
          "y": 2797
        label:
          text: Bathroom
          x: 2457
          "y": 2797
          offset_y: 35
        outline:
          - - 2390
            - 2690
          - - 2525
            - 2690
          - - 2525
            - 2905
          - - 2390
            - 2905
      - id: "3"
        icon:
          name: mdi:broom
          x: 3262
          "y": 2740
        label:
          text: Living Room
          x: 3262
          "y": 2740
          offset_y: 35
        outline:
          - - 3050
            - 2545
          - - 3475
            - 2545
          - - 3475
            - 2935
          - - 3050
            - 2935
      - id: "4"
        icon:
          name: mdi:broom
          x: 2767
          "y": 3127
        label:
          text: Hallway
          x: 2767
          "y": 3127
          offset_y: 35
        outline:
          - - 2385
            - 2890
          - - 3150
            - 2890
          - - 3150
            - 3365
          - - 2385
            - 3365
      - id: "6"
        icon:
          name: mdi:broom
          x: 3312
          "y": 3137
        label:
          text: Dining Room
          x: 3312
          "y": 3137
          offset_y: 35
        outline:
          - - 3150
            - 2915
          - - 3475
            - 2915
          - - 3475
            - 3360
          - - 3150
            - 3360
      - id: "7"
        icon:
          name: mdi:broom
          x: 2822
          "y": 3255
        label:
          text: Toilet
          x: 2822
          "y": 3255
          offset_y: 35
        outline:
          - - 2785
            - 3195
          - - 2860
            - 3195
          - - 2860
            - 3315
          - - 2785
            - 3315
      - id: "8"
        icon:
          name: mdi:broom
          x: 2582
          "y": 3200
        label:
          text: Guest Room
          x: 2582
          "y": 3200
          offset_y: 35
        outline:
          - - 2400
            - 3035
          - - 2765
            - 3035
          - - 2765
            - 3365
          - - 2400
            - 3365
    variables: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: cleaning
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: error
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:pause
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: docked
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: idle
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: error
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:stop
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: docked
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: idle
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: error
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: docked
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: docked
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: error
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: cleaning
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: min
    conditions:
      - entity:vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: min
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: min
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Medium
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: medium
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: medium
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: high
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: high
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: high
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: max
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: max
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: max
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: mop
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value: mop
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.valetudo_occasionalmurkyguanaco
        fan_speed: mop
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value_not: min
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value_not: medium
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value_not: high
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value_not: max
      - entity: vacuum.valetudo_occasionalmurkyguanaco
        attribute: fan_speed
        value_not: mop
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.vacuum_rockrobo
        fan_speed: min
tiles:
  - tile_id: battery_level
    entity: vacuum.vacuum_rockrobo
    label: Battery
    attribute: battery_level
    icon_source: vacuum.vacuum_rockrobo.attributes.battery_icon
    unit: "%"
  - tile_id: fan_speed
    entity: vacuum.valetudo_occasionalmurkyguanaco
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
additional_presets: []
```

@borgqueenx please create a new empty car try to copy and past this and lets's see if the vacuum moves or not after that you can probably carefully add the customization you had.. by the way it is a little strange..
