### DISCUSSION TITLE
Battery level in the "Vacuum Status" text

### DISCUSSION THREAD

**Discussion by zecoj** [sca075/mqtt_vacuum_camera#82] [Ideas]
### Description

As per the title, it would be awesome to have the battery level displayed along with the "Vacuum Status" text.

### Solution

for example:
valetudo: docked (100%)

**Comment by sca075** [comment]
@zecoj Thanks a lot for this proposal, it is a cool idea will do it on the next release. If you don't mind, would you star this project please, this helps a lot.

**Comment by zecoj** [comment]
Thanks. Look forward to seeing this feature!

**Comment by sca075** [comment]
@zecoj so: the implementation of this function will show the battery state when the vacuum is cleaning, moving, idle or error when docked the battery state (that is anyhow available in the card) will be not display (it makes no sense and also it is in order to avoid updates of the image while docked).
Although there will be a battery_state attribute coming our from the camera.
Hope this will meet your requirements, I mean of course it possible to use also the battery state from the vacuum but this should in any cases give an idea of what is the state of the battery in case a snapshot during error condition is taken.

**Comment by sca075** [comment]
![Screenshot 2024-02-15 at 19 21 37](https://github.com/sca075/valetudo_vacuum_camera/assets/82227818/626cb051-6087-49e9-a431-ee84256d595f)

as preview of how it looks ;)

**Comment by zecoj** [comment]
That's awesome! I think there's a good case to have it display the battery when charging: charging/docked in between longer clean for larger houses. I think if you can show the battery when docked if it is less than 100%, that would probably be a good compromise.

**Comment by sca075** [comment]
@zecoj v1.5.8 is now available, hope you will enjoy it at your disposal for any future requirements or ideas. I will try to improve it in the future release because actually I thought the same ;)

**Comment by zecoj** [comment]
Thanks for this, just tested it out and working as expected!

I still think it's good to show the battery while docked. Like I mentioned, if the vacuum is recharging whilst cleaning, it'll be good to know the battery level to know when it'll start cleaning again.

**Comment by sca075** [comment]
> Thanks for this, just tested it out and working as expected!
> 
> I still think it's good to show the battery while docked. Like I mentioned, if the vacuum is recharging whilst cleaning, it'll be good to know the battery level to know when it'll start cleaning again.

I got you point and as workaround for the time be, there is the possibility to use the tile in the card to see the battery level.
```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.valetudo_v1_silenttepidstinkbug_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_silenttepidstinkbug
vacuum_platform: Hypfer/Valetudo
internal_variables:
  topic: valetudo/SilentTepidStinkbug
....

tiles:
  - tile_id: battery_level
    entity: vacuum.valetudo_silenttepidstinkbug
    label: Battery
    attribute: battery_level
    icon_source: vacuum.valetudo_silenttepidstinkbug.attributes.battery_icon
    unit: '%'
....
```
But as mentioned above (as per the camera need to catch when the vacuum is connected to MQTT and change the label text to docked) it will be possible to to have the Docked/Charging -> Docked (Battery: 100%) transition. I'm confident on your kind understanding, technically the camera suspend the image creation when the vacuum is docked (so the status text become a little more complex).. I would need to move the text refresh in a new thread  to do not overload home assistant.. As well if I understand you want to charge the battery and then send the robot to another room for example? this can be done with the automations and the battery level in the camera attributes is updated.
As soon I'm done with it, I will get in contact with you here in GitHub.
