### ISSUE TITLE
Vacuums entity id with "_" such as "myvacuum_floor" Colours Config Not Possible.

### ISSUE THREAD

**Issue by sca075** [sca075/mqtt_vacuum_camera#209]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

It was reported already earlier, that sometime in the configuration of the Colours of the map only one colour is configurable. 
Thanks once again @tomlut I was able to reproduce the phenomena. 

### What version of an integration has described problem?

2024.07.3

### What was the last working version of an integration?

not specified 

### What vacuum model do you have problems with?

Roborock.S5

### Please firmware installed on your Vacuum.

all

### What type of platform you use?

ARM (Raspberry Pi, Odroid, etc.) > 4GB

### What version of Home Assistant do you use?

2024.7.2

### What type of installation are you running?

Home Assistant OS

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode) text will be auto formatted to code.

```shell
2024-07-18 12:22:18.807 INFO (MainThread) [custom_components.mqtt_vacuum_camera.config_flow] roborock_downstairs_camera: Options Configuration Started.
2024-07-18 12:22:18.809 WARNING (MainThread) [custom_components.mqtt_vacuum_camera.utils.users_data] File not found: /config/.storage/valetudo_camera/room_data_roborock.json
2024-07-18 12:22:18.809 INFO (MainThread) [custom_components.mqtt_vacuum_camera.config_flow] Floor Colour Configuration Started.
```

### Function, that in your opinion is creating the issue.

Room Names Advanced Option

### Additional information

The issue is in the config flow:
https://github.com/sca075/mqtt_vacuum_camera/blob/b015d0989b1f282f2d6934c5b4d88b2c8120e76f/custom_components/mqtt_vacuum_camera/config_flow.py#L185

This line split the name of the Vacuum and the file room_data_roborock.json is search instead of room_data_roborock_downstairs.json.

**Comment by sca075** [comment]
https://github.com/sca075/mqtt_vacuum_camera/discussions/179#discussioncomment-10085949

Another possible issue with it thanks @EnUfor for the report.
In summary I just release 2024.07.04b0 and I'm will to close those issues with the rooms colours once per all with the next version scheduled for the end of next week.

As soon the rooms attribute is completed, the data are stored in shard variable this shared variable is actually used to write the files room_data_robotname. 

In order to understand better the issue I would need datas from your side such as the state attribute of the camera. Bellow example from my S5.
```
friendly_name: roborock_downstairs Camera
vacuum_battery: 100%
vacuum_position: 
x: 2556
'y': 2581
angle: 178
in_room: Living Room

vacuum_topic: valetudo/roborock_downstairs
vacuum_status: docked
json_data: Success
vacuum_json_id: 6960cbdd-1bbb-498b-b777-7254873702e1
calibration_points: 
- vacuum:
    x: 2965
    'y': 2829
  map:
    x: 0
    'y': 0
- vacuum:
    x: 1609
    'y': 2829
  map:
    x: 1224
    'y': 0
- vacuum:
    x: 1609
    'y': 2075
  map:
    x: 1224
    'y': 688
- vacuum:
    x: 2965
    'y': 2075
  map:
    x: 0
    'y': 688

snapshot: false
rooms: 
'16':
  number: '16'
  outline:
    - - 2220
      - 2305
    - - 2795
      - 2305
    - - 2795
      - 2740
    - - 2220
      - 2740
  name: Living Room
  x: 2507
  'y': 2522
'17':
  number: '17'
  outline:
    - - 2490
      - 2195
    - - 2720
      - 2195
    - - 2720
      - 2325
    - - 2490
      - 2325
  name: Kitchen
  x: 2605
  'y': 2260
'18':
  number: '18'
  outline:
    - - 2165
      - 2155
    - - 2350
      - 2155
    - - 2350
      - 2335
    - - 2165
      - 2335
  name: Bath Room
  x: 2257
  'y': 2245
'19':
  number: '19'
  outline:
    - - 2050
      - 2175
    - - 2220
      - 2175
    - - 2220
      - 2475
    - - 2050
      - 2475
  name: Entrance
  x: 2135
  'y': 2325
'20':
  number: '20'
  outline:
    - - 1760
      - 2415
    - - 2210
      - 2415
    - - 2210
      - 2745
    - - 1760
      - 2745
  name: Bedroom
  x: 1985
  'y': 2580
```

The logs of the camera especially from snapshot.py are important too:

```
2024-07-18 17:07:30.678 DEBUG (roborock_downstairs_snapshot_0) [custom_components.mqtt_vacuum_camera.utils.users_data] >>>>>>> Number of Segments detected: 5
2024-07-18 17:07:30.680 INFO (roborock_downstairs_snapshot_0) [custom_components.mqtt_vacuum_camera.snapshots.snapshot] Rooms data saved for roborock_downstairs.
2024-07-18 17:07:30.696 DEBUG (silenttepidstinkbug_snapshot_0) [custom_components.mqtt_vacuum_camera.snapshots.snapshot] Adding /config/.storage/valetudo_camera/silenttepidstinkbug.log to the ZIP archive
2024-07-18 17:07:30.699 DEBUG (silenttepidstinkbug_snapshot_0) [custom_components.mqtt_vacuum_camera.snapshots.snapshot] Adding /config/.storage/valetudo_camera/silenttepidstinkbug.png to the ZIP archive
2024-07-18 17:07:30.700 DEBUG (roborock_downstairs_snapshot_0) [custom_components.mqtt_vacuum_camera.snapshots.snapshot] Adding /config/.storage/valetudo_camera/roborock_downstairs.json to the ZIP archive
2024-07-18 17:07:30.707 DEBUG (roborock_downstairs_snapshot_0) [custom_components.mqtt_vacuum_camera.snapshots.snapshot] Adding /config/.storage/valetudo_camera/roborock_downstairs.log to the ZIP archive
2024-07-18 17:07:30.710 DEBUG (roborock_downstairs_snapshot_0) [custom_components.mqtt_vacuum_camera.snapshots.snapshot] Adding /config/.storage/valetudo_camera/roborock_downstairs.png to the ZIP archive
2024-07-18 17:07:30.833 DEBUG (silenttepidstinkbug_snapshot_0) [custom_components.mqtt_vacuum_camera.snapshots.snapshot]
```

Thanks in advance for the cooperation ;)

**Comment by EnUfor** [comment]
Here are both states:
<details>
  <summary>Roborock S7</summary>
  
```YAML
access_token: REDACTED
model_name: MQTT Vacuums
brand: MQTT Vacuum Camera
friendly_name: roborocks7 Camera
vacuum_battery: 100%
vacuum_position: 
x: 2560
'y': 2578
angle: 181
in_room: Dining Room

vacuum_topic: valetudo/roborocks7
vacuum_status: docked
json_data: Success
vacuum_json_id: 05eb3b7b-aefb-45bb-becb-740aa9ddc52b
calibration_points: 
- vacuum:
    x: 2949
    'y': 2210
  map:
    x: 0
    'y': 0
- vacuum:
    x: 2949
    'y': 3564
  map:
    x: 1354
    'y': 0
- vacuum:
    x: 1965
    'y': 3564
  map:
    x: 1354
    'y': 984
- vacuum:
    x: 1965
    'y': 2210
  map:
    x: 0
    'y': 984

snapshot: false
rooms: 
'16':
  number: '16'
  outline:
    - - 2225
      - 3215
    - - 2465
      - 3215
    - - 2465
      - 3530
    - - 2225
      - 3530
  name: Nail Room
  x: 2345
  'y': 3372
'17':
  number: '17'
  outline:
    - - 2020
      - 2270
    - - 2470
      - 2270
    - - 2470
      - 2870
    - - 2020
      - 2870
  name: Kitchen
  x: 2245
  'y': 2570
'18':
  number: '18'
  outline:
    - - 2750
      - 2615
    - - 2895
      - 2615
    - - 2895
      - 2830
    - - 2750
      - 2830
  name: Entrance
  x: 2822
  'y': 2722
'19':
  number: '19'
  outline:
    - - 2470
      - 2265
    - - 2895
      - 2265
    - - 2895
      - 2635
    - - 2470
      - 2635
  name: Dining Room
  x: 2682
  'y': 2450
'20':
  number: '20'
  outline:
    - - 2325
      - 2810
    - - 2890
      - 2810
    - - 2890
      - 3235
    - - 2325
      - 3235
  name: Living Room
  x: 2607
  'y': 3022

entity_picture: /api/camera_proxy/camera.roborocks7_camera?token=REDACTED
supported_features: 1
```
  
</details>

<details>
  <summary>Dreame L10 Pro</summary>
  
```YAML
friendly_name: L10 Pro Camera
supported_features: 1
access_token: REDACTED
model_name: MQTT Vacuums
brand: MQTT Vacuum Camera
vacuum_battery: 100%
vacuum_topic: valetudo/l10pro
vacuum_status: docked
snapshot: false
entity_picture: /api/camera_proxy/camera.l10_pro_camera?token=REDACTED
vacuum_position: 
x: 3193
'y': 3255
angle: 272

json_data: Success
vacuum_json_id: 998fabcf-b181-4bd7-bd76-055f5634c744
calibration_points: 
- vacuum:
    x: 2520
    'y': 3125
  map:
    x: 0
    'y': 0
- vacuum:
    x: 3669
    'y': 3125
  map:
    x: 1149
    'y': 0
- vacuum:
    x: 3669
    'y': 4039
  map:
    x: 1149
    'y': 914
- vacuum:
    x: 2520
    'y': 4039
  map:
    x: 0
    'y': 914

rooms: 
'1':
  number: '1'
  outline:
    - - 2625
      - 3230
    - - 3155
      - 3230
    - - 3155
      - 3625
    - - 2625
      - 3625
  name: Guest Bedroom
  x: 2890
  'y': 3427
'3':
  number: '3'
  outline:
    - - 3175
      - 3230
    - - 3565
      - 3230
    - - 3565
      - 3745
    - - 3175
      - 3745
  name: Bedroom
  x: 3370
  'y': 3487
'4':
  number: '4'
  outline:
    - - 2625
      - 3620
    - - 2840
      - 3620
    - - 2840
      - 3830
    - - 2625
      - 3830
  name: Bathroom
  x: 2732
  'y': 3725
'5':
  number: '5'
  outline:
    - - 2845
      - 3430
    - - 3395
      - 3430
    - - 3395
      - 3960
    - - 2845
      - 3960
  name: Hallway
  x: 3120
  'y': 3695
```
  
</details>

I enabled debugging for the add-on and simulated changing colors for both vacuums, but I did not see any log messages pertaining to _snapshot.py_. Am I looking at the correct logs?
