### ISSUE TITLE
Highlight when the Vacuum is in Error State.

### ISSUE THREAD

**Issue by sca075** [sca075/mqtt_vacuum_camera#281]
### Description

Reported from @carefulcomputer on [Show error in card when vacuum gets stuck or runs into error](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/776)

### Solution

Few suggestions to make it even better (not sure what all is possible)

Provide a slight red tint to whole image (which would indicate the error)
If possible draw a circle or replace robot icon (or enlarge, different color etc) to make location of robot more prominent

### Context

Description
Currently when vacuum gets stuck , the card doesn't show any error. So it is hard to know that it got stuck.

Solution
It will be nice for card to show the error and last known position prominently. That will allow for quick rescue of the bot

**Comment by sca075** [comment]
The camera can auto export a snapshot of the image when the vacuum state is "error". A notification can be trigger via Home Assistant automations or scenes.  When the error is detected  the integration is going to provide also the event to home assistant "valetudo_error":
```yaml
event_type: valetudo_error
data:
  entity_id: vacuum.silenttepidstinkbug
  error: "{error}"
origin: LOCAL
time_fired: "2024-11-26T18:32:39.959478+00:00"
context:
  id: 01JDMVYE8QJE9RHAMXDPWN4Z5J
  parent_id: null
  user_id: null
```
The robot outer borders colours will change to RED as advised in order to highlight the error condition.
