### ISSUE TITLE
Obstacle View - Missing IP address

### ISSUE THREAD

**Issue by sca075** [sca075/mqtt_vacuum_camera#294]
Reported by @marvinwankersteen.

Where does the IP address/hostname from which HA downloads the image come from? Because mine says:

```
obstacles: 
- point:
    x: 2978
    'y': 2450
  label: Obstacle (70%)
  link: >-
    http://None/api/v2/robot/capabilities/ObstacleImagesCapability/img/cc948342-e069-5d68-aab3-8c8cf93e75ab
```

HA logs:
```
2024-12-05 18:20:43.315 ERROR (ThreadPoolExecutor-6_0) [custom_components.mqtt_vacuum_camera.camera] Error downloading image: Cannot connect to host none:80 ssl:default [Domain name not found]
```

My workaround in HA currently looks like this:
```
grep none /etc/hosts
<ip-of-robot> none
```

_Originally posted by @marvinwankersteen in https://github.com/sca075/mqtt_vacuum_camera/issues/286#issuecomment-2521007266_
