### ISSUE TITLE
Reset Trims after map change

### ISSUE THREAD

**Issue by OlafKocanda** [sca075/mqtt_vacuum_camera#311]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi there,

I am using the [maploader](https://github.com/pkoehlers/maploader/tree/main) with bc my apartment is not fully accessible for the Dreame LS10u. I have flashed my robot with Valetudo. After deleting the map with valetudo and creating a new map, it seems to be cut off.

Here the Vacuum Camera Screenshot:
![image](https://github.com/user-attachments/assets/1f2a3712-a08c-48a5-b0b5-11711516782f)

And here the one from the Valetudo Map integration:
![image](https://github.com/user-attachments/assets/3eb61a23-5f4b-4389-b078-9db494b03ae5)

Also, when switchin maps, it seems not to automatically reload. Is there a way to reload the map?

### What version of an integration has described problem?

2024.12.2

### What vacuum model do you have problems with?

Dreame LS10u

### Please firmware installed on your Vacuum.

2024.11.0 (Valetudo)

### What type of platform you use?

ARM (Raspberry Pi, Odroid, etc.) > 4GB

### What version of Home Assistant do you use?

2025.1.2

### What type of installation are you running?

Home Assistant OS

### Function, that in your opinion is creating the issue.

None

**Comment by sca075** [comment]
@OlafKocanda did it work for you? would be really appreciated your kind feedback, and..if all is okay please consider to star this project ;) by the way.. I will soon implement a maploader map change "action" as I did for Rand256 this should avoid duplicated services calls, meaning changing the map from the camera service will automatically wait for the map to change and then reset the trims.. I'm keeping this open for tracking purposes.

**Comment by OlafKocanda** [comment]
> @OlafKocanda did it work for you? would be really appreciated your kind feedback, and..if all is okay please consider to star this project ;) by the way.. I will soon implement a maploader map change "action" as I did for Rand256 this should avoid duplicated services calls, meaning changing the map from the camera service will automatically wait for the map to change and then reset the trims.. I'm keeping this open for tracking purposes.

Thanks, that's a good one and solves part 1/2. I added it to an automation, however, I think the changing of the map is not always triggering an "update of the map". I tried it with disabling and enabling the integration but had no luck so far. Here is the automation:

```alias: "Helene Wischer Map Change to Kitchen + Living Room "
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_select.map_helene
    to: Kitchen + Living Room
conditions: []
actions:
  - action: mqtt.publish
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      topic: valetudo/HeleneWischer/maploader/map/load
      payload: main
  - action: mqtt_vacuum_camera.reset_trims
    metadata: {}
    data: {}
  - action: homeassistant.disable_config_entry
    metadata: {}
    data:
      config_entry_id: 01JHAPP43RSX1GKDX1HVQBZ2H6
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - action: homeassistant.enable_config_entry
    metadata: {}
    data:
      config_entry_id: 01JHAPP43RSX1GKDX1HVQBZ2H6
mode: single
```

**Comment by OlafKocanda** [comment]
I think i found it... there is a service command to reload the integration. So i created a dropdown with two options and two automations which first send the mqtt command for the maploader, then reload the mqtt camera integration and after 5 seconds pause trim the map. If anyone needs the code:
```
alias: "Helene Wischer Map Change to Kitchen + Living Room "
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_select.map_helene
    to: Kitchen + Living Room
conditions: []
actions:
  - action: mqtt.publish
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      topic: valetudo/HeleneWischer/maploader/map/load
      payload: main
  - action: homeassistant.reload_config_entry
    metadata: {}
    data: {}
    target:
      entity_id: camera.helene_wischer_camera
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
    enabled: true
  - action: mqtt_vacuum_camera.reset_trims
    metadata: {}
    data: {}
mode: single
```
